### ISSUE TITLE
The sandbox.yaml reference in the containerd-env-setup.md document has issues

### ISSUE THREAD

**Issue by whygyc** [dragonflyoss/image-service#1496]
Related issues: https://github.com/kubernetes-sigs/cri-tools/issues/1273

The `nydus-sandbox.yaml` does not specify a uid which causes the `crictl rmp` to fail
```
metadata:
  attempt: 1
  name: nydus-sandbox
  namespace: default
log_directory: /tmp
linux:
  security_context:
    namespace_options:
      network: 2
```

As a test example, uid can be specified as an arbitrary string, like: 
```
metadata:
  attempt: 1
  name: nydus-sandbox
  namespace: default
  uid: nydus-sandbox-test
```

This issue will be fixed in the new version, but it remains a problem for those using slightly earlier versions of crictl.
